name: Go CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger
        run: swag init

      - name: Install OpenAPI to Postman converter
        run: npm install -g openapi-to-postmanv2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Convert Swagger to Postman Collection
        run: |
          openapi2postmanv2 -s docs/swagger.json -o postman-output.json -p
          cat postman-output.json
          jq '.output[0].data' postman-output.json > postman.json
          ls -la

      - name: Update Postman Collection
        run: |
          curl -X PUT "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_UID }}" \
            -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data-binary @postman.json

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/haidarr-h/backend-go:latest .

      - name: Push Docker image
        run: docker push ghcr.io/haidarr-h/backend-go:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/backend-go
            docker compose pull
            docker compose up -d
